backend:
  name: github
  repo: irfan-wahyu/irfan.site
  branch: main

local_backend: true

# Jalur pencarian gambar yang aman untuk Astro & Decap
public_folder: /irfan.site/images
media_folder: public/images

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Subtitle",
          name: "subtitle",
          widget: "string",
          required: false,
        }
      - {
          label: "Cover Thumbnail",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - {
          label: "Year",
          name: "year",
          widget: "number",
          value_type: "int",
          default: 2026,
        }
      - {
          label: "Duration",
          name: "duration",
          widget: "string",
          default: "1 Minggu",
        }
      - {
          label: "Status",
          name: "status",
          widget: "select",
          options: ["Completed", "In Progress", "On Hold"],
          default: "Completed",
        }
      - {
          label: "Medium",
          name: "medium",
          widget: "string",
          default: "Motion Graphics",
        }
      - {
          label: "Tools",
          name: "tools",
          widget: "list",
          field: { label: "Tool", name: "tool", widget: "string" },
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          field: { label: "Tag", name: "tag", widget: "string" },
        }
      - {
          label: "Featured Project?",
          name: "featured",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Order",
          name: "order",
          widget: "number",
          value_type: "int",
          default: 1,
        }
      - { label: "Body", name: "body", widget: "markdown", allow_images: true }
